version: '3.9'

services:
  node:
    build: .
    container_name: portfolio
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    command: >
      sh -c "
        npm install &&
        npm run serve -- --port 8080
      "