version: "3.7"

services:

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - ${WEB_PORT:-8080}:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/log/access.log:/var/log/nginx/access.log
            - ./nginx/log/error.log:/var/log/nginx/error.log
  
    vue:
        build: ./vue/
        container_name: vue
        volumes:
            - ../vue:/mnt/vue/
        command: [sh, -c, npm install && npm run serve -- --port 8080]
