version: "3"

services:

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../vue/public:/var/www/public
  
    vue:
        build: ./vue/
        container_name: vue
        volumes:
            - ../vue:/mnt/vue/
        stdin_open: true
        tty: true
        command: [sh, -c, npm install && npm run serve -- --port 8080]
        environment:
            - CHOKIDAR_USEPOLLING=true
