version: "3.8"

services:

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
    vue:
        build: ./vue/
        container_name: vue
        volumes:
            - ../vue:/mnt/vue/
        command: [sh, -c, npm install && npm run serve -- --port 8080]
