version: '3.9'

services:

  # web
  node:
    image: node:14.17.0-alpine
    container_name: 'portfolio'
    working_dir: /app
    volumes:
      - ../vue:/app
    ports:
      - '${WEB_PORT:-8080}:8080'
    command: >
      sh -c "
        npm install &&
        npm run serve -- --port 8080
      "
    env_file:
      - .env

  # cms
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi