version: '3.9'

services:

  # web
  node:
    image: node:16.15.0-alpine
    container_name: 'portfolio'
    working_dir: /app
    volumes:
      - ../vue:/app
    ports:
      - '${WEB_PORT:-8080}:8080'
    command: >
      sh -c "
        npm install &&
        npm run serve -- --port 8080
      "
