version: "3.7"

services:

    # web
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - ${WEB_PORT:-8080}:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/log/:/var/log/nginx/
  
    vue:
        build: ./vue/
        container_name: vue
        volumes:
            - ../vue:/mnt/vue/
        command: [sh, -c, npm install && npm run serve -- --port 8080]
    
    # cms
    strapi:
        image: strapi/strapi
        environment:
            DATABASE_CLIENT: mysql
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: strapi
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
            DATABASE_SSL: 'false'
        volumes:
            - ./app:/srv/app
        ports:
            - '1337:1337'
        depends_on:
            - mysql

    mysql:
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: strapi
            MYSQL_DATABASE: strapi
            MYSQL_USER: strapi
            MYSQL_PASSWORD: strapi